3 create sidebar component
Fansoa/otonom pull request #28
Opened 2024-07-31 12:32 UTC by Fansoa

2024-07-31 12:34 UTC, Fansoa commented
Réflexion posé sur le discord forbees

Dans mon application, j'intègre une sidebar qui doit afficher le lien de la page actuelle différemment de ceux des autres.

Sachant que je suis dans un contexte Next plusieurs solutions s'offre à moi:
Intégration de la sidebar de façon statique pour chaque page
Intégration au niveau du layout avec un custom hook qui récupère le pathName et qui le met en relation avec le le tableau de configuration passé en props du la sidebar
 
J'ai opté pour la deuxième solution mais la logique abstraite de cette implémentation impose un cadre d'utilisation.. mais d'un autre coté je n'intègre qu'une seule fois le composant dans le layout.

La première implémentation est plus performante sur le plan logiciel et n'implique pas de logique abstraite.

2024-07-31 12:38 UTC, Fansoa commented
Concernant le hook, je me demande si je ne devrais pas plutôt le placer au niveau du composant plutôt qu'au niveau de la page où il est appelé.

2024-07-31 12:53 UTC, CinquinAndy requested changes

2024-07-31 12:53 UTC, CinquinAndy commented on app/(protected)/modules/hooks/useCurrentNavigation/index.tsx
> +const useCurrentNavigation = () => {
L'idée est bonne et c'est une "bonne" pratique en ReactJS, mais pas en NextJS, le soucis en faisant ça, c'est que à chaque modification de quelque chose dans ton hook TOUT les composants enfants sont re-rendu dynamiquement et re créer dans ton DOM

Soucis en terme de perf assez conséquent, car tout les éléments enfants seront re calculer alors que ce n'est pas nécessaire 

Le hook général comme ça, est en général à éviter en NextJS sauf si justement tu veux re -render le site, (genre mise en place d'un thème en mode light/dark assez complexe)

2024-07-31 12:53 UTC, CinquinAndy commented on app/(protected)/modules/hooks/useCurrentNavigation/index.tsx
> +  const secondSegmentPath = splitedPath[2];
à la place de split comme ça, tu pourrais faire une expression régulière pour match seulement une partie de ta chaine

2024-07-31 12:53 UTC, CinquinAndy commented on app/(protected)/modules/hooks/useCurrentNavigation/index.tsx
> +
Genre toute la partie logique là, peut être remplacé par quelque chose du genre : 
```
const pathname = usePathname();

  const isActive = (href: string) => {
    if (href === '/') {
      return pathname === href;
    }
    return pathname.startsWith(href);
  };
```

2024-07-31 12:53 UTC, CinquinAndy commented on app/(protected)/modules/layout.tsx
> +import useCurrentNavigation from "@/app/(protected)/modules/hooks/useCurrentNavigation/index.tsx";
Le hook pourrait simplement être supprimer par un composant "nav" externalisé, avec un peux de logique client à l'interieur avec le "use client" dedans 

et laisser celui là en serveur side

2024-07-31 12:53 UTC, CinquinAndy commented on app/(protected)/modules/layout.tsx
> +import useCurrentNavigation from "@/app/(protected)/modules/hooks/useCurrentNavigation/index.tsx";
d'ailleurs un "layout" en "use client" c'est une mauvaise pratique -> tout les enfants seront clients du coup 
et on veut éviter ça, car next ne pourra pas pré calculer les éléments pour le client en avance

2024-07-31 12:53 UTC, CinquinAndy commented on package.json
> +    "@headlessui/react": "^2.1.2",
de façon général, il vaut mieux éviter les "^" , c'est une mauvaise pratique courante en js, mais souvent, à cause du fait que le semver est pas forcément très bien suivis, une "minor" peut être une breaking change pour toi, sans que tu le prévois / que tu le veuille, 
donc il vaut mieux lock les versions et mettre un renovate par dessus 

(c'est du détail, mais ça peut faire tomber une prod, c'est du vécu mdr)

2024-07-31 12:53 UTC, CinquinAndy commented on package.json
>      "@supabase/supabase-js": "latest",
typiquement le latest c'est du suicide

2024-07-31 12:54 UTC, CinquinAndy commented
report du commentaire sur discord, tout les commentaires seront au même endroit comme ça : 
Next à un système très chouette de page / layout / et surtout de cache interne des composants / requêtes
- Genre un truc du genre en terme de composant (layout.js): 
```ts
export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body>
        <header>
          <Nav/>
        </header>
        ...
        <main>{children}</main>
        ...
      </body>
    </html>
  );
}
```

Pour avoir la logique de façon à ce que ça soit différent en fonction de chaque page, dans le composant Nav tu peux faire : 
```ts
'use client';

import { usePathname } from 'next/navigation';
import Link from 'next/link';

export default function Nav({ routes }) {
  const routes = [
    { path: '/', label: '..' },
    { path: '/about', label: '..' },
    { path: '/contact', label: '..' },
  ];
  const pathname = usePathname();

  return (
    <nav>
      {routes.map((route) => (
        <Link 
          key={route.path} 
          href={route.path}
          className={pathname === route.path ? 'underline' : ''}
        >
          {route.label}
        </Link>
      ))}
    </nav>
  );
}
```

-> Comme ça il y a JUSTE le composant nav qui est côté client

2024-07-31 12:58 UTC, CinquinAndy commented on package.json
>      "@supabase/supabase-js": "latest",
Exemple pour expliquer ce que je dit ici, 

Imagine tu utilise une librairie de chart (genre chart.js)
un des composants est sympa, tu l'utilises, tu veux forcer le design d'une certaine manière à match ton UI, donc tu fou un peux de custom dessus, tu changes deux trois classes et tu désactive un focus par exemple. 

Là le mec qui gère la lib se rend compte que le fonctionnement d'un des focus est bizarre, il le corrige, il change une petite ligne, il passe ça en mineur. 
Le chapeau de la dépendance fait que toi ça le met à jour automatiquement au prochain déploiement / modif, 

Sauf que cette modif est pas compatible avec ton implémentation, paff, ça crash, ta prod tombe, pourtant aucune major, aucune breaking change, une toute petite modif, mais sans contrôle de ta part 

-> conclusion : on fait des tests e2e / unitaires + on fait confiance en personne + on fou un renovate par dessus pour les mises à jour de sécurité, mais on check avant que rien ne pète avant de foutre en prod !

2024-07-31 13:00 UTC, CinquinAndy commented
> Concernant le hook, je me demande si je ne devrais pas plutôt le placer au niveau du composant plutôt qu'au niveau de la page où il est appelé.
> 
> Les deux façons de faire sont logiques mais la question se pose tout de même.
> 
> Si c'était dans un projet avec plus de collaborateurs, un nouveau développeur aurait potentiellement du mal à se servir du composant. Après étant donné que ce composant n'est appelé qu'un seule fois dans l'application, on peut dire que c'est tolérable.

du coup, à mon avis, le mieux est de ne pas faire de hook du tout, pour ce genre d'utilisation tu n'en a pas besoin, 
Si tu veux montrer ton utilisation des hooks, fait un thème dans ton app, c'est un cas "courant", qui fonctionne bien, ou un système de traduction, why no't

2024-07-31 13:26 UTC, Fansoa commented on package.json
>      "@supabase/supabase-js": "latest",
Effectivement! C'est un reliquat de l'installation de Next avec Supabase

2024-07-31 13:30 UTC, Fansoa commented on package.json
> +    "@headlessui/react": "^2.1.2",
Je n'avais encore jamais fait attention à ce genre de détail mais j'en ai profité pour googler ça.

Je suis tombé sur cet [article de blog](https://michaelsoolee.com/npm-package-tilde-caret/) qui m'a permis d'en apprendre un peu plus.

J'ai supprimé les `^`.

2024-07-31 13:32 UTC, Fansoa commented on package.json
>      "@supabase/supabase-js": "latest",
> typiquement le latest c'est du suicide

Effectivement! C'est un reliquat de l'installation de Next avec Supabase

2024-07-31 13:36 UTC, Fansoa commented on package.json
>      "@supabase/supabase-js": "latest",
> Exemple pour expliquer ce que je dit ici,
> 
> Imagine tu utilise une librairie de chart (genre chart.js) un des composants est sympa, tu l'utilises, tu veux forcer le design d'une certaine manière à match ton UI, donc tu fou un peux de custom dessus, tu changes deux trois classes et tu désactive un focus par exemple.
> 
> Là le mec qui gère la lib se rend compte que le fonctionnement d'un des focus est bizarre, il le corrige, il change une petite ligne, il passe ça en mineur. Le chapeau de la dépendance fait que toi ça le met à jour automatiquement au prochain déploiement / modif,
> 
> Sauf que cette modif est pas compatible avec ton implémentation, paff, ça crash, ta prod tombe, pourtant aucune major, aucune breaking change, une toute petite modif, mais sans contrôle de ta part
> 
> -> conclusion : on fait des tests e2e / unitaires + on fait confiance en personne + on fou un renovate par dessus pour les mises à jour de sécurité, mais on check avant que rien ne pète avant de foutre en prod !

J'ai entendu certains développeurs expliquer qu'ils utilisaient des adapters pour leurs dépendances. Tu pense que cela peut permettre d'éviter ce genre de problème? Si bien-sûr, on a le luxe de faire cela..

2024-07-31 15:57 UTC, Fansoa commented on app/(protected)/modules/hooks/useCurrentNavigation/index.tsx
> +  const secondSegmentPath = splitedPath[2];
const path = '/modules/mealworm';
const regex = /([a-zA-Z0-9])\w+/g;
const [firstPathSegment, secondPathSegment] = path.match(regex);

console.log(firstPathSegment, secondPathSegment);

Tu pensais à cela? Si oui, pourquoi?

J'ai fais quelques tests dans la console chrome et visiblement la fonction split semble plus rapide:
![image](https://github.com/user-attachments/assets/2ffb0f3d-e173-47eb-9a0c-2f467ff3e3e5)

J'ai testé avec ce code: 
```
const path = '/modules/mealworm';

console.time("regex")
const regex = /([a-zA-Z0-9])\w+/g;
const [firstSegment, secondSegment] = path.match(regex);
console.timeLog("regex")

console.time("split")
const splitedPath = path.split("/");
const [_, firstSegmentPath, secondSegmentPath] = splitedPath;
console.timeLog("split")
```

2024-07-31 20:28 UTC, Fansoa commented
Je pense séparer l'affichage et la logique en utilisant un custom hook.

Aussi, cela me permettra de mocker le hook et donc de rendre le composant utilisable dans storybook, qu'en pense-tu?

2024-08-01 15:51 UTC, CinquinAndy commented on app/(protected)/modules/hooks/useCurrentNavigation/index.tsx
> +  const secondSegmentPath = splitedPath[2];
Enfaite, je part en terme de lisibilité, et te praticité, 
Si tu pense atomic design, il vaut mieux essayer de rendre les choses le plus générique possible,

La regex permet, en gros, de voir d'un seul coup d'oeil ce que tu cherches à faire et en 1-2-3 lignes de code, tu as le resultat attendu. 
En terme de maintenabilité, tu te retrouve avec quelque chose de bien plus lisible et maintenable (on oublie pas qu'on est PAS en big data, et donc les petits optis de perf de l'ordre du 0.0X ms ... on s'en fiche...

SURTOUT, que à ce niveau là de détail, entre deux execution du code, et sur deux machines différentes, et deux environnements différents, avec le même code, on se retrouve potentiellement avec des perfs complétements différentes et même inversées ( il faudrait tester avec des milliers / centaines de milliers de tests )

2024-08-01 18:51 UTC, merged